export const ADD_POST = "ADD-POST";
export const DELETE_POST = "DELETE-POST";
export const UPDATE_NEW_POST_TEXT = "UPDATE-NEW-POST-TEXT";
export const SET_PROFILE = "SET-PROFILE";
export const SET_STATUS = "SET-STATUS";

export const SEND_NEW_MESSAGE = "ADD-UPDATE-NEW-MESSAGE-TEXT";

export const FOLLOW_USER = "FOLLOW-USER";
export const UNFOLLOW_USER = "UNFOLLOW-USER";
export const SET_USERS = "SET-USERS";
export const SET_TOTAL_USERS_COUNT = "SET-TOTAL-USERS-COUNT";
export const UPDATE_PAGE_NUMBER = "UPDATE-PAGE-NUMBER";
export const SET_IS_FETCHING = "SET-IS-FETCHING";

export const SET_USER_AUTHENTICATION = "SET-USER-AUTHENTICATION";
export const LOGOUT_USER = "LOGOUT-USER";

export const INITIALIZE = "INITIALIZE"
export const DESTROY = "DESTROY"
