export const ADD_POST = "ADD-POST";
export const UPDATE_NEW_POST_TEXT = "UPDATE-NEW-POST-TEXT";
export const UPDATE_NEW_MESSAGE_TEXT = "UPDATE-NEW-MESSAGE-TEXT";
export const SEND_NEW_MESSAGE = "ADD-UPDATE-NEW-MESSAGE-TEXT";

export const FOLLOW_USER = "FOLLOW-USER";
export const UNFOLLOW_USER = "UNFOLLOW-USER";
export const SET_USERS = "SET-USERS";
